data:
  test_size: 0.25
  random_state: 42

model:
  random_state: 42
  scale_pos_weight: 2.77

  # Logistic Regression
  lr_max_iter: 2000

  # Random Forest
  rf_n_estimators: 400

  # XGBoost
  xgb_n_estimators: 600
  xgb_max_depth: 6
  xgb_lr: 0.01
  xgb_subsample: 0.9
  xgb_colsample: 0.9